#:schema node_modules/wrangler/config-schema.json
name = "summarize-pdf"
main = "src/index.ts"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[[r2_buckets]]
bucket_name = "resumes"
preview_bucket_name="resumes-test"
binding = "resumes"

[[d1_databases]]
binding = "DB"
database_name = "resumes"
database_id = "7050a432-c6c4-44e2-be43-4b2e492b344b"

[observability]
enabled = true

[ai]
binding = "AI"
